"""
    VAG API

    Web-API für Echtzeitinformationen der VAG Nürnberg  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.vag.model.haltestelle_dto import HaltestelleDto
from deutschland.vag.model.metadata import Metadata

from deutschland import vag

globals()["HaltestelleDto"] = HaltestelleDto
globals()["Metadata"] = Metadata
from deutschland.vag.model.haltestellen_api_response import HaltestellenAPIResponse


class TestHaltestellenAPIResponse(unittest.TestCase):
    """HaltestellenAPIResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHaltestellenAPIResponse(self):
        """Test HaltestellenAPIResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HaltestellenAPIResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
