"""
    VAG API

    Web-API für Echtzeitinformationen der VAG Nürnberg  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.vag.model.fahrt_dto import FahrtDto
from deutschland.vag.model.fahrweg_halteposition_dto import FahrwegHaltepositionDto
from deutschland.vag.model.metadata import Metadata

from deutschland import vag

globals()["FahrtDto"] = FahrtDto
globals()["FahrwegHaltepositionDto"] = FahrwegHaltepositionDto
globals()["Metadata"] = Metadata
from deutschland.vag.model.fahrten_api_response import FahrtenAPIResponse


class TestFahrtenAPIResponse(unittest.TestCase):
    """FahrtenAPIResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFahrtenAPIResponse(self):
        """Test FahrtenAPIResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FahrtenAPIResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
