"""
    VAG API

    Web-API für Echtzeitinformationen der VAG Nürnberg  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.vag.model.fahrweg_halteposition_dto import FahrwegHaltepositionDto

from deutschland import vag


class TestFahrwegHaltepositionDto(unittest.TestCase):
    """FahrwegHaltepositionDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFahrwegHaltepositionDto(self):
        """Test FahrwegHaltepositionDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FahrwegHaltepositionDto()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
