"""
    VAG API

    Web-API für Echtzeitinformationen der VAG Nürnberg  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.vag.api.abfahrten_api import AbfahrtenApi  # noqa: E501

from deutschland import vag


class TestAbfahrtenApi(unittest.TestCase):
    """AbfahrtenApi unit test stubs"""

    def setUp(self):
        self.api = AbfahrtenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_abfahrten_get1(self):
        """Test case for abfahrten_get1

        Liefert die Abfahrten zu einer bestimmten Haltestelle  # noqa: E501
        """
        pass

    def test_abfahrten_get2(self):
        """Test case for abfahrten_get2

        Liefert die Abfahrten zu einer bestimmten Haltestelle  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
