"""
    VAG API

    Web-API für Echtzeitinformationen der VAG Nürnberg  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.vag.model.haltestelle_dto import HaltestelleDto

from deutschland import vag


class TestHaltestelleDto(unittest.TestCase):
    """HaltestelleDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHaltestelleDto(self):
        """Test HaltestelleDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HaltestelleDto()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
