"""
    VAG API

    Web-API für Echtzeitinformationen der VAG Nürnberg  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.vag.model.fahrt_dto import FahrtDto

from deutschland import vag


class TestFahrtDto(unittest.TestCase):
    """FahrtDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFahrtDto(self):
        """Test FahrtDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FahrtDto()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
